version: '3.8'

services:
  mysql-exchange:
    image: mysql:9.1.0
    container_name: mysql-exchange
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: currency_db
    command: --secure-file-priv="" --local-infile=1
    ports:
      - "3308:3306"
    volumes:
      - finance_exchange:/var/lib/mysql  # 외부 볼륨 사용

volumes:
  finance_exchange:
    external: true  # 외부 볼륨 선언


