version: '3.8'  

services:
  mysql-exchange:  
    image: mysql:latest 
    container_name: mysql-exchange  
    restart: always  
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   
    ports:  
      - "3308:3306"  
    volumes:  
      - mysql_data:/var/lib/mysql  

volumes:  
  mysql_data:
